"""Initial migration

Revision ID: a0e010aa7b08
Revises: 
Create Date: 2025-11-08 23:48:11.817773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e010aa7b08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('REPORTED', 'INVESTIGATING', 'IDENTIFIED', 'RESOLVING', 'RESOLVED', 'CLOSED', 'REOPENED', name='incidentstatus'), nullable=False),
    sa.Column('source', sa.Enum('OPERATOR', 'MONITORING', 'PARTNER', 'CUSTOMER', 'AUTOMATION', 'SECURITY', name='incidentsource'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index('idx_incident_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_incident_source', ['source'], unique=False)
        batch_op.create_index('idx_incident_status', ['status'], unique=False)
        batch_op.create_index('idx_status_created', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index('idx_status_created')
        batch_op.drop_index('idx_incident_status')
        batch_op.drop_index('idx_incident_source')
        batch_op.drop_index('idx_incident_created_at')

    op.drop_table('incidents')
    # ### end Alembic commands ###
